### ISSUE TITLE
Issues with pyvbox 

### ISSUE THREAD

**Issue by malpwn** [qeeqbox/Rhino#1]
Hi first of I'd like you to know this is a great project ! 
I have done everything accordingly but for some reasons I have the vm is not registered error 

I have checked with vboxmanage and the vm is registered and accessible :) but for some reason the backend worker thread refuses to acknowledge the existence 

workers_api_1       | [2020-05-05 07:10:58,560: WARNING/Process-1:1] 2020-05-05 14:10:58.560720 b387a960-68d1-4429-a685-9c2a9b491486 turn_off Failed 0x80bb0001 (Could not find a registered machine named 'guestsandbox')
workers_api_1       | [2020-05-05 07:10:58,560: INFO/Process-1:1] [datetime.datetime(2020, 5, 5, 14, 10, 58, 560720), u'b387a960-68d1-4429-a685-9c2a9b491486', "turn_off Failed 0x80bb0001 (Could not find a registered machine named 'guestsandbox')", '\x1b[91m>\x1b[0m']

**Comment by qeeqbox** [comment]
Thanks & good first issue, can you tell me the project version (Check info file inside Rhino project)

**Comment by malpwn** [comment]
Apologies for the delay it's 2020.V.01.07

**Comment by malpwn** [comment]
Weird thing I noticed when docker-compose starts the workers suddenly the registered target vm changes it's status to 'inaccessible' before that it shows up in the list :/ 

Apologies in advance if it is expected behavior which I am skeptical about

**Comment by qeeqbox** [comment]
I just updated the project with new testing logics and some other fixes https://github.com/qeeqbox/Rhino/commit/e6b2300fbfe65a770f4ead93569e005ce5128465

git clone https://github.com/qeeqbox/Rhino.git
cd Rhino
chmod +x ./run.sh
./run.sh auto_configure_dummy

Open the web interface -> settings -> test and paste the output here

**Comment by malpwn** [comment]
Latest commits fixes the issue
