### ISSUE TITLE
uploadtovm feature issue

### ISSUE THREAD

**Issue by malpwn** [qeeqbox/Rhino#2]
Again the issue is regarding pyvbox 
After enabling logging for 
progress = gs.file_copy_to_guest(path.join(folder,action["input"]["filename"]),action["input"]["filepath"], [FileCopyFlag(0)])
in vboxparser.py

workers_api_1       | [2020-05-24 10:24:35,723: WARNING/Process-1:3] 2020-05-24 17:24:35.722899 f1639ff0-877b-46ff-a84c-010014d28d2d result code: Querying information on for 'C:\Users\test\Desktop\file.exe' failed: VERR_INTERNAL_ERROR_5
progress.result_code =  -2135228411

where C:\Users\pwn\Desktop\file.exe is the file path specified

**Comment by malpwn** [comment]
Further investigation leads to 
workers_api_1       | VBoxManage: error: File copy failed
workers_api_1       | VBoxManage: error: Querying information on for '"C:\Users\test\Desktop\putty.exe"' failed: VERR_INTERNAL_ERROR_5
workers_api_1       | VBoxManage: error: Details: code VBOX_E_IPRT_ERROR (0x80bb0005), component GuestSessionWrap, interface IGuestSession
workers_api_1       | VBoxManage: error: Context: "RTEXITCODE gctlHandleCopy(PGCTLCMDCTX, int, char**, bool)" at line 1940 of file VBoxManageGuestCtrl.cpp
workers_api_1       | VBoxManage: error: Querying information on for '"C:\Users\test\Desktop\putty.exe"' failed: VERR_INTERNAL_ERROR_5.

**Comment by qeeqbox** [comment]
1) What is the windows VM's VBoxGuestAdditions version? 
2) What UAC and Defender settings do you have on that windows VM?
3) Is that file malicious or not?

**Comment by qeeqbox** [comment]
If you still facing the same issue, I might be able to check it in depth sometime next week (I was busy working on a new project that I'm pushing to GitHub tomorrow!)

**Comment by qeeqbox** [comment]
It's related to my previous response
